"""Tests for AI Safety & Bias Detection module."""

import pytest
from src.safety.bias_scanner import scan_bias, scan_content_bias


# ── Bias scanner tests ──────────────────────────────────────────────────────

def test_scan_empty_prompt():
    """Scanning with no inputs should flag insufficient data."""
    result = scan_bias(system_name="test-agent")
    assert result.findings_count >= 1
    assert result.score < 100


def test_scan_minimal_prompt():
    """A basic prompt with no safety boundaries should flag multiple issues."""
    result = scan_bias(
        system_name="basic-agent",
        system_prompt="You are a helpful assistant.",
    )
    assert result.findings_count >= 4  # Missing fairness, oversight, appeal, transparency, etc.
    assert result.risk_level in ("CRITICAL", "HIGH")
    assert any(f["category"] == "safety_boundary" for f in result.findings)


def test_scan_good_prompt():
    """A well-crafted prompt with safety measures should score higher."""
    result = scan_bias(
        system_name="safe-agent",
        system_prompt="""You are a fair and unbiased hiring assistant.
        Treat all candidates equally regardless of race, gender, age, religion, or disability.
        Apply bias mitigation by focusing only on job-relevant qualifications.
        All decisions require human review before being finalized.
        Candidates may appeal any automated decision and request human reconsideration.
        This is an AI-assisted tool — all recommendations are generated by machine learning.
        Training data is balanced and representative across demographics.
        Protected attributes like gender and race must not influence scoring.
        Monitor output decisions weekly for disparate impact.""",
    )
    assert result.score > 80
    assert result.findings_count < 3


def test_stereotype_detection():
    """Should detect stereotypical associations."""
    result = scan_bias(
        system_name="test",
        model_output="Women are naturally more emotional and nurturing than men.",
    )
    assert any(f["category"] == "stereotype" for f in result.findings)


def test_toxicity_detection():
    """Should detect toxic content patterns."""
    result = scan_bias(
        system_name="test",
        model_output="All Muslims are extremists and should not be trusted.",
    )
    has_toxicity = any(f["category"] == "toxicity" for f in result.findings)
    has_stereotype = any(f["category"] == "stereotype" for f in result.findings)
    assert has_toxicity or has_stereotype


def test_sentiment_disparity():
    """Should detect negative sentiment correlated with protected groups."""
    result = scan_bias(
        system_name="test",
        model_output="The elderly applicant was rejected as unqualified and risky.",
    )
    assert any(f["category"] == "sentiment_disparity" for f in result.findings)


def test_disparate_impact():
    """Should detect disparate impact in decision logs using four-fifths rule."""
    decisions = []
    # Group A: 80% approval
    for i in range(50):
        decisions.append({
            "outcome": "approved" if i < 40 else "denied",
            "demographics": {"gender": "male"},
        })
    # Group B: 30% approval (well below 4/5 of 80%)
    for i in range(50):
        decisions.append({
            "outcome": "approved" if i < 15 else "denied",
            "demographics": {"gender": "female"},
        })

    result = scan_bias(system_name="lending-model", decisions=decisions)
    assert any(f["category"] == "disparate_impact" for f in result.findings)
    assert any("female" in f.get("evidence", "") for f in result.findings)


def test_disparate_impact_fair():
    """Fair decisions should not trigger disparate impact findings."""
    decisions = []
    for i in range(50):
        decisions.append({
            "outcome": "approved" if i < 40 else "denied",
            "demographics": {"gender": "male"},
        })
    for i in range(50):
        decisions.append({
            "outcome": "approved" if i < 38 else "denied",
            "demographics": {"gender": "female"},
        })

    result = scan_bias(system_name="fair-model", decisions=decisions)
    assert not any(f["category"] == "disparate_impact" for f in result.findings)


# ── Content scan tests ──────────────────────────────────────────────────────

def test_content_scan_clean():
    """Clean content should pass."""
    result = scan_content_bias("The quarterly report shows 15% revenue growth.")
    assert result["is_safe"] is True
    assert result["bias_detected"] is False
    assert result["toxicity_detected"] is False


def test_content_scan_biased():
    """Biased content should be flagged."""
    result = scan_content_bias(
        "Elderly candidates are always confused and slow during interviews.",
        source="interview_notes",
    )
    assert result["is_safe"] is False
    assert result["source"] == "interview_notes"


def test_content_scan_toxic():
    """Toxic content should be flagged."""
    result = scan_content_bias("All immigrants are criminals stealing our jobs.")
    assert result["is_safe"] is False
    assert result["toxicity_detected"] or result["bias_detected"]


# ── Score/risk level tests ──────────────────────────────────────────────────

def test_score_range():
    """Score should always be 0-100."""
    result = scan_bias(system_name="test", system_prompt="Be helpful.")
    assert 0 <= result.score <= 100


def test_risk_levels():
    """Risk levels should be valid."""
    result = scan_bias(system_name="test")
    assert result.risk_level in ("CRITICAL", "HIGH", "MEDIUM", "LOW")
